dataset:
  args:
    aug_type: "sim_sim" # due to the type of the GPU available in the HPC, the limited memory of these GPU, this the largest batch size we can use for each GPU.
    total_batch_size: 128

learning_model:
  name: 'bcl_model'

classifier:
  name: 'Class_Balanced_Softmax'
  args:
    power_law: 1.0